jenkins-home:
  image: jenkins
  volumes:
   - /data/jenkins-home:/var/jenkins_home
  command: /bin/true

jenkins-master:
  image: jenkins
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes_from:
    - jenkins-home
